version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
          - "6541:5432"
    environment:
          - POSTGRES_DB=stats
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=root

  ewm-service:
    ports:
      - "8080:8080"
    build: ./main-service
    depends_on:
      - ewm-db
      - stats-server
    container_name: ewm-service

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    container_name: ewm-db
    environment:
      - POSTGRES_DB=mainservice
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
